version: "3.8"
networks:
  mynetwork:
    driver: bridge
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=RefkaDB
    ports:
      - 3307:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    image: back
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8090:8080

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/eventsProject?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./m2:/root/.m2
    networks:
      - mynetwork